version: '3'
services:
  api:
    build: .
    command: rails server -b 0.0.0.0 -p 3001
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    tty: true
    stdin_open: true

  postgres:
    image: 'postgres:12.4'
    volumes:
      - 'postgres:/var/lib/postgresql/data/pgdata'
    ports:
      - '5432:5432'
    env_file: .env

volumes:
  postgres:
