const MOCK_OPEN_BETS = [
    {   // single game bet
        "id": 1,
        "userId": 2,
        "poolId": 1,
        "entryId": 2,
        "amount": "20.0",
        "result": null,
        "createdAt": "2020-12-25T21:22:02.156Z",
        "updatedAt": "2020-12-25T21:22:02.156Z",
        "payout": "30.0",
        "fixtures": [
            {
                "id": 1,
                "sport": "americanfootball_nfl",
                "startTime": "2020-12-25T22:28:49.243Z",
                "homeTeamId": 1,
                "homeTeamName": 'Kansas City Chiefs',
                "awayTeamId": 2,
                "awayTeamName": "Denver Broncos",
                "homeScore": null,
                "awayScore": null,
                "status": "scheduled",
                "createdAt": "2020-12-24T22:28:50.333Z",
                "updatedAt": "2020-12-24T22:28:50.333Z",
                "locked": true,
                "bets": [
                    {
                        "id": 75,
                        // "oddId": 3,
                        "userId": 2,
                        "poolId": 3,
                        "entryId": 14,
                        "amount": "20.0",
                        "result": null,
                        "createdAt": "2020-12-17T07:01:19.365Z",
                        "updatedAt": "2020-12-18T04:48:27.040Z",
                        "payout": "30.0",
                        "homeTeamName": "Las Vegas Raiders",
                        "awayTeamName": "Los Angeles Chargers",
                        "odd": {
                            "id": 3,
                            "type": "spread",
                            "fixtureId": 1,
                            "ratio": "1.9",
                            "metric": "-3.5",
                            "teamId": 1,
                            "player": null,
                            "active": true,
                            "createdAt": "2020-12-24T22:28:50.404Z",
                            "updatedAt": "2020-12-24T22:28:50.404Z",
                            "teamName": "Kansas City Chiefs",
                            "american": -111,
                        },
                        "result": "won"
                    },
                ],
            },
        ],
    },
    {   // single fixture parlay
        "id": 2,
        "userId": 2,
        "poolId": 1,
        "entryId": 2,
        "amount": "30.0",
        "result": null,
        "createdAt": "2020-12-25T21:22:02.156Z",
        "updatedAt": "2020-12-25T21:22:02.156Z",
        "payout": "40.0",
        "fixtures": [
            {
                "id": 1,
                "sport": "americanfootball_nfl",
                "startTime": "2020-12-25T22:28:49.243Z",
                "homeTeamId": 1,
                "homeTeamName": "Kansas City Chiefs",
                "awayTeamId": 2,
                "awayTeamName": "Denver Broncos",
                "homeScore": null,
                "awayScore": null,
                "status": "scheduled",
                "createdAt": "2020-12-24T22:28:50.333Z",
                "updatedAt": "2020-12-24T22:28:50.333Z",
                "locked": true,
                "bets": [
                    {
                        "id": 7,
                        // "oddId": 3,
                        "userId": 2,
                        "poolId": 1,
                        "entryId": 14,
                        "amount": null,
                        "result": null,
                        "createdAt": "2020-12-17T07:01:19.365Z",
                        "updatedAt": "2020-12-18T04:48:27.040Z",
                        "payout": null,
                        "homeTeamName": "Kansas City Chiefs",
                        "awayTeamName": "Denver Broncos",
                        "odd": {
                            "id": 3,
                            "type": "spread",
                            "fixtureId": 1,
                            "ratio": "1.9",
                            "metric": "-3.5",
                            "teamId": 1,
                            "player": null,
                            "active": true,
                            "createdAt": "2020-12-24T22:28:50.404Z",
                            "updatedAt": "2020-12-24T22:28:50.404Z",
                            "teamName": "Kansas City Chiefs",
                            "american": -111,
                        },
                        "result": "in-progress",
                    },
                    {
                        "id": 8,
                        // "oddId": 5,
                        "userId": 2,
                        "poolId": 1,
                        "entryId": 14,
                        "amount": null,
                        "result": null,
                        "createdAt": "2020-12-17T07:01:19.365Z",
                        "updatedAt": "2020-12-18T04:48:27.040Z",
                        "payout": null,
                        "homeTeamName": "Kansas City Chiefs",
                        "awayTeamName": "Denver Broncos",
                        "odd": {
                            "id": 5,
                            "type": "over",
                            "fixtureId": 1,
                            "ratio": "1.9",
                            "metric": "50.5",
                            "teamId": null,
                            "player": null,
                            "active": true,
                            "createdAt": "2020-12-24T22:28:50.438Z",
                            "updatedAt": "2020-12-24T22:28:50.438Z",
                            "teamName": null,
                            "american": -111,
                        },
                        "result": "draw",
                    },
                    {
                        "id": 8,
                        // "oddId": 5,
                        "userId": 2,
                        "poolId": 1,
                        "entryId": 14,
                        "amount": null,
                        "result": null,
                        "createdAt": "2020-12-17T07:01:19.365Z",
                        "updatedAt": "2020-12-18T04:48:27.040Z",
                        "payout": null,
                        "homeTeamName": "Kansas City Chiefs",
                        "awayTeamName": "Denver Broncos",
                        "odd": {
                            "id": 1,
                            "type": "money_line",
                            "fixtureId": 1,
                            "ratio": "1.5",
                            "metric": null,
                            "teamId": 1,
                            "player": null,
                            "active": true,
                            "createdAt": "2020-12-24T22:28:50.369Z",
                            "updatedAt": "2020-12-24T22:28:50.369Z",
                            "teamName": "Kansas City Chiefs",
                            "american": -200,
                        },
                        "result": "lost",
                    },
                ],
            },
        ],
    },
    {   // multi-fixture parlay
        "id": 3,
        "userId": 2,
        "poolId": 1,
        "entryId": 2,
        "amount": "30.0",
        "result": null,
        "createdAt": "2020-12-25T21:22:02.156Z",
        "updatedAt": "2020-12-25T21:22:02.156Z",
        "payout": "40.0",
        "fixtures": [
            {
                "id": 1,
                "sport": "americanfootball_nfl",
                "startTime": "2020-12-25T22:28:49.243Z",
                "homeTeamId": 1,
                "homeTeamName": "Kansas City Chiefs",
                "awayTeamId": 2,
                "awayTeamName": "Denver Broncos",
                "homeScore": null,
                "awayScore": null,
                "status": "scheduled",
                "createdAt": "2020-12-24T22:28:50.333Z",
                "updatedAt": "2020-12-24T22:28:50.333Z",
                "locked": true,
                "bets": [
                    {
                        "id": 7,
                        "userId": 2,
                        "poolId": 1,
                        "entryId": 14,
                        "amount": null,
                        "result": null,
                        "createdAt": "2020-12-17T07:01:19.365Z",
                        "updatedAt": "2020-12-18T04:48:27.040Z",
                        "payout": null,
                        "homeTeamName": "Kansas City Chiefs",
                        "awayTeamName": "Denver Broncos",
                        "odd": {
                            "id": 3,
                            "type": "spread",
                            "fixtureId": 1,
                            "ratio": "1.9",
                            "metric": "-3.5",
                            "teamId": 1,
                            "player": null,
                            "active": true,
                            "createdAt": "2020-12-24T22:28:50.404Z",
                            "updatedAt": "2020-12-24T22:28:50.404Z",
                            "teamName": "Kansas City Chiefs",
                            "american": -111,
                        },
                        "result": null,
                    },
                ],
            },
            {
                "id": 2,
                "sport": "americanfootball_nfl",
                "startTime": "2020-12-25T22:28:49.243Z",
                "homeTeamId": 3,
                "homeTeamName": "Seattle Seahawks",
                "awayTeamId": 4,
                "awayTeamName": "Arizona Cardinals",
                "homeScore": null,
                "awayScore": null,
                "status": "scheduled",
                "createdAt": "2020-12-24T22:28:50.333Z",
                "updatedAt": "2020-12-24T22:28:50.333Z",
                "locked": false,
                "bets": [
                    {
                        "id": 8,
                        "userId": 2,
                        "poolId": 1,
                        "entryId": 14,
                        "amount": null,
                        "result": null,
                        "createdAt": "2020-12-17T07:01:19.365Z",
                        "updatedAt": "2020-12-18T04:48:27.040Z",
                        "payout": null,
                        "homeTeamName": "Seattle Seahawks",
                        "awayTeamName": "Arizona Cardinals",
                        "odd": {
                            "id": 7,
                            "type": "money_line",
                            "fixtureId": 2,
                            "ratio": "1.5",
                            "metric": null,
                            "teamId": 4,
                            "player": null,
                            "active": true,
                            "createdAt": "2020-12-24T22:28:50.404Z",
                            "updatedAt": "2020-12-24T22:28:50.404Z",
                            "teamName": "Seattle Seahawks",
                            "american": -200,
                        },
                        "result": null,
                    }
                ],
            },
        ],
    },
];

export default MOCK_OPEN_BETS;
